GET http://localhost:5030/games

###

GET http://localhost:5030/games/4

###
POST http://localhost:5030/games
Content-Type: application/json

{
       "name": "COD",
       "genre":"action",
       "price": 20.22,
       "releaseDate": "2015-10-22"
}

###
PUT http://localhost:5030/games/3
Content-Type: application/json

{
       "name": "Spiderman",
       "genre":"RPG",
       "price": 145.22,
       "releaseDate": "2020-10-22"
}

###
DELETE http://localhost:5030/games/2

